baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "CaseIT 2021"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# main site menu
[menu]
  # the site main navigation
  [[menu.nav]]
    identifier = "competition-section"
    name = "Competition"
    url = "/competition/"
    weight = 1
  [[menu.nav]]
    identifier = "sponsorship-section"
    name = "Sponsorship"
    url = "/sponsorship/"
    weight = 2
  [[menu.nav]]
    identifier = "about-section"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    identifier = "contact-section"
    name = "Contact"
    url = "/contact/"
    weight = 4
  [[menu.nav]]
    identifier = "hiring-section"
    name = "Join Us"
    url = "/hiring/"
    weight = 4
  
  # navigation under competition section
  [[menu.competition]]
    identifier = "competition-overview"
    name = "Overview"
    url = "/competition/"
    weight = 1

  [[menu.competition]]
    identifier = "competition-information"
    name = "Information"
    url = "/competition/information/"
    weight = 2

  [[menu.competition]]
    identifier = "competition-registration"
    name = "Registration"
    url = "/competition/registration/"
    weight = 3

  # navigation under sponsorship section
  [[menu.sponsorship]]
    identifier = "sponsorship-overview"
    name = "Overview"
    url = "/sponsorship/"
    weight = 1

  [[menu.sponsorship]]
    identifier = "sponsorship-opportunities"
    name = "Sponsorship Opportunities"
    url = "/sponsorship/opportunities/"
    weight = 2