backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

logo_url: "https://caseit.org/img/logo/CaseIT_Black.svg"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
    # not finished, to be implemented
  - name: "competition-information"
    label: "Competition Information"
    folder: "site/content/competition/information"
    create: true
    # not to list pages that marked "ignore", eg _index.md
    filter: { field: "netlify-cms-collection-ignore", value: false }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "Short text that helps viewer to understand what where are they going before clicking into this article",
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
          hint: "Banner of this article, an image smaller than 1663 x 1080 is recommended",
        }
      - {
          label: "Lead",
          name: "lead",
          widget: "markdown",
          required: false,
          hint: "A short summery/key point of content that used to capture viewer's attention",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      # add a record under navigation
      - {
          name: "menu",
          widget: "hidden",
          hidden: true,
          fields:
            [
              {
                name: "competition",
                widget: "hidden",
                hidden: true,
                fields:
                  [
                    {
                      name: "parent",
                      widget: "hidden",
                      default: "competition-information",
                    },
                  ],
              },
            ],
        }
      - {
          name: "type",
          widget: "hidden",
          hidden: true,
          default: "competition-information",
        }
      - {
          label: "netlify-cms-collection-ignore",
          name: netlify-cms-collection-ignore,
          widget: hidden,
          default: false,
        }
  # ==============================================================
  # Hiring Collections
  # ==============================================================
  - label: "Hiring - Available Positions"
    name: "hiring-available-positions"
    create: true
    folder: "site/content/hiring"
    # not to list pages that marked "ignore", eg _index.md
    filter: { field: "netlify-cms-collection-ignore", value: false }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          hint: "a short blurb about what this position about",
        }
      - {
          label: "Lead",
          name: "lead",
          widget: "markdown",
          hint: "A leading paragarph in the job description page",
        }
      - {
          label: "Position Type",
          name: "position_type",
          widget: "select",
          options:
            [
              { label: "Associate", value: "associate" },
              { label: "Director", value: "director" },
              { label: "Vice Chair", value: "vice-chair" },
              { label: "Chair", value: "chair" },
            ],
        }
      - {
          label: "Position(s) Available",
          name: "position_available",
          widget: "number",
          options: ["associate", "director", "chair", "vice-chair"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "unsorted-pages"
    label: "Unsorted Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - {
              label: "Pitch Blurb 1",
              name: pitch1,
              widget: object,
              fields:
                [
                  { label: "Image", name: "imageUrl", widget: image },
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                  { label: "CTA Text", name: "ctaText", widget: string },
                ],
            }
          - {
              label: "Pitch Blurb 2",
              name: pitch2,
              widget: object,
              fields:
                [
                  { label: "Image", name: "imageUrl", widget: image },
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                  { label: "CTA Text", name: "ctaText", widget: string },
                ],
            }
          - {
              label: "CaseIT Going Online",
              name: caseitGoingOnline,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: text },
                  { label: "CTA Text", name: "ctaText", widget: string },
                  {
                    label: "Resources",
                    name: "resources",
                    widget: list,
                    fields:
                      [
                        { label: "Heading", name: "heading", widget: string },
                        { label: "Text", name: "text", widget: text },
                      ],
                  },
                ],
            }
          - {
              label: "CaseIT 2020 Photo Grid",
              name: caseit2020,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Text", name: "text", widget: "text" },
                ],
            }
          - {
              label: "Sponsors",
              name: "sponsors",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "imageUrl", widget: image },
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                  { label: "CTA Text", name: "ctaText", widget: string },
                ],
            }
          - {
              label: "Ending CTA",
              name: "endingCtaBlock",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "imageUrl", widget: image },
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Text", name: "text", widget: "text" },
                  {
                    label: "Student TA Text",
                    name: "ctaTextStudent",
                    widget: string,
                  },
                  {
                    label: "Coach CTA Text",
                    name: "ctaTextCoach",
                    widget: string,
                  },
                ],
            }

      # ==============================================================
      # Contact page
      # ==============================================================

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
              - label: Link
                name: link
                widget: string
          - label: Top Questions
            name: top_questions
            widget: list
            fields:
              - label: Questions
                name: heading
                widget: string
              - label: Answer
                name: text
                widget: markdown

      # ==============================================================
      # Hiring page
      # ==============================================================
      - file: "site/content/hiring/_index.md"
        label: "Hiring Page"
        name: "hiring"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
          - {
              label: "Application Form Link",
              name: application_link,
              widget: string,
            }
          - { label: "Cta Blurb", name: cta_blurb, widget: string }

  # ==============================================================
  # Competition Overview Section
  # ==============================================================
  - name: "comeptition-section"
    label: "Competition Section"
    files:
      - file: "site/content/competition/_index.md"
        label: "Competition Overview"
        name: "competition-overview"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Intro Blurb", name: description, widget: markdown }
          - label: "netlify-cms-collection-ignore"
            name: netlify-cms-collection-ignore
            widget: hidden
            default: true
      # ==============================================================
      # Competition Information Section
      # ==============================================================
      # competition information page
      - file: "site/content/competition/information/_index.md"
        label: "Competition Information"
        name: "competition-information"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Intro Blurb", name: description, widget: markdown }
          - label: "Important Dates/Announcement Timeline"
            name: important_dates
            widget: list
            fields:
              - label: "Time"
                name: heading
                widget: string
              - label: "Things Happen"
                name: text
                widget: string
              - label: "active"
                name: active
                widget: boolean
          - label: "Email Subscription Section"
            name: email_subscription
            widget: object
            fields:
              [
                { label: "Heading", name: "heading", widget: "string" },
                { label: "Blurb", name: "text", widget: "markdown" },
                { label: "CTA Text", name: "ctaText", widget: "string" },
              ]
          - label: "netlify-cms-collection-ignore"
            name: netlify-cms-collection-ignore
            widget: hidden
            value: true
            default: true

  # ==============================================================
  # Sponsorship Section
  # ==============================================================
  - name: "sponsorship-section"
    label: "Sponsorship Section"
    files:
      #sponsorship overview
      - file: "site/content/sponsorship/_index.md"
        label: "Sponsorship Overview Page"
        name: "sponsorship-overview"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Intro Blurb", name: description, widget: markdown }
          - label: "Pitch"
            name: pitch
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Benefits
                name: benefits
                widget: list
                fields:
                  - label: Text
                    name: text
                    widget: markdown
              - label: Image
                name: imageUrl
                widget: image
          - label: "Our 2020 Sponsors"
            name: our_2020_sponsors
            widget: object
            fields:
              - { label: "Heading", name: heading, widget: string }
              - { label: "Text", name: text, widget: markdown }
          - label: "Sponsorship Opportunities"
            name: sponsorship_opportunities
            widget: object
            fields:
              - { label: "Heading", name: heading, widget: string }
              - { label: "Text", name: text, widget: markdown }
              - { label: "CTA Text", name: ctaText, widget: string }

  # ==============================================================
  # About Section
  # ==============================================================
  - name: "about-section"
    label: "About Section"
    files:
      #chairs welcome
      - file: "site/content/welcoming.md"
        label: "Chair's Welcome"
        name: "chairs-welcome"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Cover Image", name: image, widget: image }
          - { label: "Author", name: author, widget: string }
          - { label: "Signiture Image", name: signiture_image, widget: image }
          - {
              label: "Written Date",
              name: written_date,
              widget: string,
              hint: "MM/DD/YYYY",
            }
          - { label: "Description", name: description, widget: string }
          - { label: "Body", name: body, widget: markdown }
      #history
      - file: "site/content/history.md"
        label: "History"
        name: "history"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Cover Image", name: image, widget: image }
          - { label: "Description", name: description, widget: string }
          - { label: "Body", name: body, widget: markdown }

  # ==============================================================
  # Storing Data
  # ==============================================================
  - label: "Downloadable Resources"
    name: "resources"
    editor:
      preview: false
    files:
      - file: "site/data/downloadableResources.json"
        label: "Downloadable Resources list"
        name: "downloadable_documents"
        fields:
          - label: "Downloadable Documents"
            name: "documents"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "File", name: "URL", widget: "file" }
              - {
                  label: "Description Title",
                  hint: "This will show up as a header in the CTA (Call to Action) module",
                  name: "descriptionTitle",
                  widget: "string",
                }
              - {
                  label: "Description Blurb",
                  name: "descriptionBlurb",
                  hint: "This blurb will show up in the CTA (Call to Action) module",
                  widget: "markdown",
                }
